language: python


jobs:
  include:
    - name: ITSXPRESS
      cache: pip
      python:
        - "3.6"
      # command to install dependencies
      # before_install:
      #   # - wget https://sourceforge.net/projects/bbmap/files/BBMap_38.60.tar.gz -O /tmp/BBMap_38.60.tar.gz
      #   # - tar -xvf /tmp/BBMap_38.60.tar.gz
      #   # - export PATH=$PATH:$PWD/bbmap
      #   # - wget https://github.com/torognes/vsearch/releases/download/v2.13.6/vsearch-2.13.6-linux-x86_64.tar.gz -O /tmp/vsearch-2.13.6-linux-x86_64.tar.gz
      #   # - tar -xvf /tmp/vsearch-2.13.6-linux-x86_64.tar.gz
      #   # - export PATH=$PATH:$PWD/vsearch-2.13.6-linux-x86_64/bin
      #   # - wget http://eddylab.org/software/hmmer3/3.1b2/hmmer-3.1b2-linux-intel-x86_64.tar.gz -O /tmp/hmmer-3.1b2-linux-intel-x86_64.tar.gz
      #   # - tar -xvf /tmp/hmmer-3.1b2-linux-intel-x86_64.tar.gz
      #   # - ls -la
      #   # - export PATH=$PATH:$PWD/hmmer-3.1b2-linux-intel-x86_64/binaries

      install:
        - pip install codecov
        - pip install -vvv .
        - pip install nose-exclude
      # command to run tests
      script:
        - nosetests --exclude-dir tests_plugin --with-coverage # or py.test for Python versions 3.5 and below

      after_success:
        - codecov



    - name: QIIME2 ITSXPRESS
      dist: trusty

      # command to install dependencies
      before_install:
      - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      - export MINICONDAS="$HOME/miniconda"
      - bash miniconda.sh -b -p $MINICONDAS
      - export PATH="$MINICONDAS/bin:$PATH"
      - conda config --set always_yes yes
      - conda update -q conda
      - wget https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py36-linux-conda.yml
      - conda env create -n test-env --file qiime2-latest-py36-linux-conda.yml
      - source activate test-env
      install:
        - conda config --add channels bioconda
        - pip install -vvv .
        - pip install codecov
        - qiime itsxpress
        - qiime dev refresh-cache
      # command to run tests
      script:
        - nosetests --with-coverage # or py.test for Python versions 3.5 and below

      after_success:
        - codecov



# notifications:
#    email:
#      - adam.rivers@usda.gov

